apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-07-02T19:22:19Z"
  labels:
    app.kubernetes.io/name: hubble-relay
    app.kubernetes.io/part-of: cilium
    k8s-app: hubble-relay
    pod-template-hash: 84cc45d558
  name: hubble-relay-84cc45d558-p4bds
  namespace: kube-system
  resourceVersion: "20350"
  uid: 2a767133-016b-4a5a-bed2-bfd307f76250
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.180.250
  clusterIPs:
  - 10.96.180.250
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32005
    port: 4245
    protocol: TCP
    targetPort: 4245
  selector:
    app.kubernetes.io/name: hubble-relay
    app.kubernetes.io/part-of: cilium
    k8s-app: hubble-relay
    pod-template-hash: 84cc45d558
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
